export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        
       
      
        {/* That's where the magic happens */}
        {children}
        
        <hr />
        <footer>
          Footer
        </footer>

      </body>
    </html>
  )
}
