import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-sans bg-gray-50 text-gray-900">
        
        <header className="bg-blue-300 p-4 shadow-md">
          <h3 className="text-2xl font-semibold text-gray-700">Main Header</h3>
        </header>
        
       
        
        {/* That's where the magic happens */}
        {children}
        
       
        
        <footer className="bg-blue-800  p-4 mt-8 shadow-md">
          <h3 className="text-2xl   text-white ">Main Footer</h3>
        </footer>

      </body>
    </html>
  )
}
