import React from 'react'

export const metadata = {
  title: 'Next.js',
  description: 'Static Metadata Generated by Next.js',
}

export const dynamic = 'force-dynamic';
export const revalidate = 60;




export default function Metadata() {
  return (
    <div>Metadata</div>
  )
}
