import React from 'react'

// Static Metadata 
export const metadata = {
  title: 'Metadata - Next.js',
  description: 'Metadata - Static Generated by Next.js',


}

export default function BlogLayout({ children } :{children: React.ReactNode}) {
  console.log(children)
  return (
    <>
    <h2 className='bg-indigo-100 px-4 py-2'>Metadata Header</h2>
    {children}
    <h2 className='bg-indigo-100 px-4 py-2'>Metadata Footer</h2>
    </>
  )
}
